version: '3.8'

services:
  monolith:
    container_name: 88motorcycle-monolith
    build:
      context: .
      dockerfile: Dockerfile.monolith
    ports:
      - "3000:3000"
      - "5433:5432" # Map container's DB port to host 5433 to avoid conflict with local postgres
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@127.0.0.1:5432/88motorcycle
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
    volumes:
      - monolith_data:/var/lib/postgresql/data
    restart: always

volumes:
  monolith_data:
